/*
 *  Nimble, an extensive application base for Grails
 *  Copyright (C) 2010 Bradley Beddoes
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

nimble {
	organization {
		name = "Systematic"
		displayname = "Systematic"
		description = "Vi cykler til arbejde"
		logo = ""
		logosmall = ""
		url = ""
	}

	layout {
		application = 'app'
		administration = 'admin'
	}

	localusers {
		authentication { enabled = true } 
		registration { enabled = false }
		provision { active = true }
	}

	messaging {
		enabled = true

		registration { subject = "Your new account is ready!" }
		passwordreset { subject = "Your password has been reset" }
		changeemail { subject = "Your email address has been changed" }
		invitation { subject = "You have a new team invitation" }

		mail {
			from = "Systematic Employees Club <mikkel.madsen@systematic.com>"
			host = "smtp.mandrillapp.com"
			port = 587
			username = System.env.MANDRILL_USERNAME?:"app24243842@heroku.com"
			password = System.env.MANDRILL_APIKEY?:"bLdBfOSCJFQ6qhXerkEzwQ" // The default is a test key, no emails will be sent unless a proper key is provided in ENV
			props = [
				"mail.smtp.protocol":"smtps",
                "mail.smtp.channel":"plain",
                "mail.smtp.auth":"true",
                "mail.debug":"false"
				]
		}
	}

	implementation {
		user = "User"
		profile = "Profile"
	}
	
	passwords {
		mustcontain {
			lowercase = false
			uppercase = false
			numbers = false
			symbols = false
		}
		minlength = 6
	}
}

environments {
	development {
		nimble {
			recaptcha {
				enabled = false
				secureapi = false

				// These keys are generated by the ReCaptcha service
				publickey = ""
				privatekey = ""

				// Include the noscript tags in the generated captcha
				noscript = true
			}
		}
	}
	production {
		nimble {
			recaptcha {
				enabled = false
				secureapi = false

				// These keys are generated by the ReCaptcha service
				publickey = ""
				privatekey = ""

				// Include the noscript tags in the generated captcha
				noscript = true
			}
		}
	}
}
