/*
 *  Nimble, an extensive application base for Grails
 *  Copyright (C) 2010 Bradley Beddoes
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

nimble {
	organization {
		name = "Systematic"
		displayname = "Systematic"
		description = "Vi cykler til arbejde"
		logo = ""
		logosmall = ""
		url = ""
		organizer {
			name = "Mikkel Madsen"
			email = "mikkel.madsen@systematic.com"
		}
	}

	layout {
		application = 'app'
		administration = 'admin'
	}

	localusers {
		authentication { enabled = true } 
		registration { enabled = false }
		provision { active = true }
	}

	messaging {
		enabled = true

		registration { subject = "Your new account is ready!" }
		passwordreset { subject = "Your password has been reset" }
		changeemail { subject = "Your email address has been changed" }
		invitation { subject = "You have a new team invitation" }

		mail {
			from = "Systematic Employees Club <mikkel.madsen@systematic.com>"
			host = "smtp.gmail.com"
			port = 465
			username = System.env.VCTA_MAIL_USERNAME?:"systematicpf@gmail.com"
                        password = System.env.VCTA_MAIL_PASSWORD?:"replace with actual pass"
			props = ["mail.smtp.auth":"true", 					   
				"mail.smtp.socketFactory.port":"465",
				"mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory",
				"mail.smtp.socketFactory.fallback":"false"]
		}
	}
	
	localusers {
		usernames {
			minlength = 2
			validregex = '[a-zA-Z0-9]*'
		}
	}

	implementation {
		user = "User"
		profile = "Profile"
	}
	
	passwords {
		mustcontain {
			lowercase = false
			uppercase = false
			numbers = false
			symbols = false
		}
		minlength = 6
	}
}

environments {
	development {
		nimble {
			recaptcha {
				enabled = false
				secureapi = false

				// These keys are generated by the ReCaptcha service
				publickey = ""
				privatekey = ""

				// Include the noscript tags in the generated captcha
				noscript = true
			}
		}
	}
	production {
		nimble {
			recaptcha {
				enabled = false
				secureapi = false

				// These keys are generated by the ReCaptcha service
				publickey = ""
				privatekey = ""

				// Include the noscript tags in the generated captcha
				noscript = true
			}
		}
	}
}
